### PR TITLE
Minor editing of markdown text

### PR DESCRIPTION
**Pull request by dkirkby**
I did some editing of the markdown text.

### CODE REVIEW

**Comment by dkirkby** [comment]
This cell is giving me an error:

```
#Now we make the interactive plot using the interact command
#we specify the values of the parameters as lists or ranges
interact(pdist,f=["Gaussian","Uniform","Binomial","Poisson","Cauchy",
                  "Chi2","Laplace","Student t","Fisher f","Beta","Gamma","Weibull"],par1=(0,10),par2=(0,10))
```

Here is the error, which might be because I need to update bokeh?

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-26-f23db3f341f4> in pdist(f, par1, par2)
      2 #and par1, par2 that are the value of two parameters of these distributions (mean,sigma etc)
      3 def pdist(f,par1=0,par2=1):
----> 4     if f=="Gaussian": dist = stats.norm(par1,par2); rr.data_source.data['y']=dist.pdf(xd)
      5     if f=="Uniform": dist = stats.uniform(par1,par2); rr.data_source.data['y']=dist.pdf(xd)
      6     if f=="Binomial": dist = stats.binom(par1,par2); rr.data_source.data['y']=dist.pmf(xd)

AttributeError: 'Figure' object has no attribute 'data_source'
```

**Comment by dkirkby** [comment]
The randomfield and basemap plots come out with a grayscale colormap.  Perhaps because seaborn is resetting the default colormap?

**Comment by dkirkby** [comment]
The last example (using astropy.cosmology) looks like it isn't complete yet?

**Comment by fjaviersanchez** [comment]
Thank you!

Yes, seaborn changes the colormap, maybe we can change it again or restart the kernel using `%reset`? I don't know what the best option is.

I didn't know what else I could add using astropy.cosmology because the notebook is pretty long already and it's likely that we will run out of time. 

About the bokeh problem, I did that example a while ago, and it worked for older versions of bokeh, and it also works in the latest one. Try to update it and if it doesn't work we can try to check tomorrow what is going on.

**Pull request merged**
